---
kind: pipeline
name: test

steps:
- name: lint
  image: arduino/arduino-cli:drone-1.0
  commands:
    # Check if the Go code is properly formatted and run the linter
    - task check
    # Ensure protobufs compile without errors
    - task protoc

- name: build
  image: arduino/arduino-cli:drone-1.0
  commands:
    - task build

- name: test
  image: arduino/arduino-cli:drone-1.0
  commands:
    - task test-unit
    - task test-legacy

- name: integration
  image: arduino/arduino-cli:drone-1.0
  commands:
    - pip install -r test/requirements.txt
    - task test-integration

- name: coverage
  # Contrary to other CI platforms, uploading reports to Codecov requires Drone to provide a token.
  # To avoid exposing the Codecov token to external PRs, we only upload coverage when we merge on
  # `master`.
  image: arduino/arduino-cli:drone-1.0
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
    - codecov -cF unit -f coverage_unit.txt -t $CODECOV_TOKEN
    - codecov -cF integ -f coverage_integ.txt -t $CODECOV_TOKEN
  when:
    branch:
      - master
    event:
      - push

---
kind: pipeline
name: release

steps:
- name: fetch
  # extra step needed to fetch tags after cloning
  image: docker:git
  commands:
  - git fetch --tags

- name: release
  image: arduino/arduino-cli:builder-0.1
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
    AWS_ACCESS_KEY_ID:
      from_secret: downloads_drone_io_aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: downloads_drone_io_aws_secret_access_key
    AWS_DEFAULT_REGION: 'us-east-1'
  commands:
    - goreleaser

trigger:
  event:
    # releases are triggered by tags only
    - tag
  status:
    # skip the release if the previous build failed
    - success
  ref:
    exclude:
    # exclude the tags used to build Docker images for drone
    - refs/tags/builder-*
    - refs/tags/drone-*

depends_on:
  - test