---
kind: pipeline
name: release

steps:
- name: fetch
  # extra step needed to fetch tags after cloning
  image: docker:git
  commands:
  - git fetch --tags

- name: release
  image: arduino/arduino-cli:builder-0.1
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
    AWS_ACCESS_KEY_ID:
      from_secret: downloads_drone_io_aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: downloads_drone_io_aws_secret_access_key
    AWS_DEFAULT_REGION: 'us-east-1'
  commands:
    - goreleaser

trigger:
  event:
    # releases are triggered by tags only
    - tag
  status:
    # skip the release if the previous build failed
    - success
  ref:
    exclude:
    # exclude the tags used to build Docker images for drone
    - refs/tags/builder-*
    - refs/tags/drone-*
    - refs/tags/nightly

depends_on:
  - test
