language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored.
before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0

install: true

script:
  # Check if the code is formatted
  - $(exit $(go fmt ./... | wc -l))
  # Run linter
  - golangci-lint run
  # Build and test
  - go build
  - go test -timeout 20m -v -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

