language: go

go:
  - 1.11.x

env:
  - DEP_VERSION="0.5.0"

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored.
before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  # Check the dependency, -skip-lock may be useful because the version are not fixed but depends
  # from the branch master of the libraries so they change very often
  - dep check -skip-vendor
  - dep ensure

script:
  # Check if the code is formatted
  - $(exit $(go fmt ./... | wc -l))
  # Run linter
  - golangci-lint run
  # Build and test
  - go build
  - go test -timeout 20m -v -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/dep