version: '2'

vars:
  TEST_VERSIONSTRING: "0.0.0-test.preview"
  TEST_COMMIT: "deadbeef"
  TEST_LDFLAGS_VALUE: >
    '-X github.com/arduino/arduino-cli/version.versionString={{.TEST_VERSIONSTRING}}
    -X github.com/arduino/arduino-cli/version.commit={{.TEST_COMMIT}}'

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -v -i

  test:
    desc: Run the full testsuite
    cmds:
      - task: test-unit
      - task: test-integration

  test-unit:
    desc: Run unit tests only
    cmds:
      - go test -short {{ default "-v" .GOFLAGS }} {{ default "./..." .TARGETS }}

  test-integration:
    desc: Run integration tests only
    cmds:
      - go test -run Integration {{ default "-v" .GOFLAGS }} {{ default "./..." .TARGETS }} -ldflags {{.TEST_LDFLAGS_VALUE}}
