name: arduino-cli
summary: CLI tool.
description: a CLI for Arduino.
  
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  arduino-cli:
    command: bin/arduino-cli
    plugs:
      - home
      - network
      - removable-media
      

parts:
  arduino-cli:
    plugin: cmake
    source: https://github.com/arduino/arduino-cli.git
    source-type: git
    override-pull: |
      git clone https://github.com/arduino/arduino-cli.git src/github.com/arduino/arduino-cli
      cd src/github.com/arduino/arduino-cli
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
    override-build: |
      export GOPATH=$PWD
      cd src/github.com/arduino/arduino-cli
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/arduino/arduino-cli/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/arduino/arduino-cli/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/arduino-cli
    build-snaps:
      - go
    build-packages:
      - git
      - sed
