name: "Formats Python code"

on:
  issue_comment:
    types: [created]

jobs:
  format:
    name: "Format Python code"
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && (contains(github.event.comment.body, '/black') || contains(github.event.comment.body, '/python-format'))

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Activate Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install Poetry
        run: pip install poetry

      - name: Formats Python files
        run: task python:format

      - name: Commits formatted Python code
        run: |
          # Check if there is something to commit
          if [ -z "$(git status --porcelain)" ]; then
            echo "Code is already formatted correctly"
            exit 0
          fi

          git config --global user.email "bot@arduino.cc"
          git config --global user.name "ArduinoBot"

          # Commit the changes
          git add .
          git commit -m "[skip changelog] Format Python code"
          git push
