name: 'Verify files formatting'

on:
  push:
    paths:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - '.prettierrc'
      - '.prettierignore'
      - '!.github/ISSUE_TEMPLATE/**/*'
      - '!.github/PULL_REQUEST_TEMPLATE.md'
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - '.prettierrc'
      - '.prettierignore'
      - '!.github/ISSUE_TEMPLATE/**/*'
      - '!.github/PULL_REQUEST_TEMPLATE.md'

jobs:
  verify-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify formatting of all files
        run: task docs:check config:check
